### ISSUE TITLE
Implement REST API handler for Queueing

### ISSUE THREAD

**Issue by thheinen** [tecracer-theinen/kitchen-static#3]
In expectation of the need to have centralized systems which assign machines and scrub them after use, develop a REST/JSON handler for these with flexible mapping. Clients can then wait in line after requesting systems with certain criteria and return them afterwards for central recycling.

```yaml
driver:
  name: static
  queueing: true
  request:
    type: json
    url: https://example.site/queueing/v1/request
  release:
    type: json
    url: https://example.site/queueing/v1/release
    method: POST
    data: { "hostname": "<%= STATIC_HOSTNAME %>"  }
```
Please respond with :+1: to express interest and increase priority.
